[package]
name = "utc_offset"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.13"
once_cell = "1.9.0"
thiserror = "1.0.30"
time = { version = "0.3.5", features = [
    "formatting",
    "local-offset",
    "parsing",
] }

[dev-dependencies]
regex = "1.5.4"